import {
  BadgeCheck,
  Bike,
  BrickWall,
  Brush,
  Car,
  ClipboardCheck,
  Drill,
  Hammer,
  HeartHandshake,
  Home,
  Package,
  PlugZap,
  Scissors,
  Settings,
  ShowerHead,
  Sparkles,
  Truck,
  Wrench,
} from "lucide-react";
import { filterWorkers } from "@/features/search/lib/search-workers";
import type { Category, Quote, Worker } from "@/types/marketplace";

export const cities = ["Sao Paulo", "Guarulhos", "Osasco", "Campinas", "Santo Andre"];

export const neighborhoods = [
  "Mooca",
  "Tatuape",
  "Pinheiros",
  "Vila Mariana",
  "Centro",
  "Jardins",
  "Santana",
];

export const categories: Category[] = [
  {
    name: "Eletricistas",
    slug: "eletricistas",
    description: "Instalacoes, quadros, manutencao e emergencia eletrica.",
    icon: PlugZap,
    professionals: 184,
    group: "Servicos tecnicos",
    subcategories: ["instalacao-em-geral", "reparos-em-geral"],
  },
  {
    name: "Encanadores",
    slug: "encanadores",
    description: "Vazamentos, reparos hidraulicos, caixas d'agua e banheiros.",
    icon: ShowerHead,
    professionals: 139,
    group: "Servicos tecnicos",
    subcategories: ["reparos-em-geral", "faz-tudo"],
  },
  {
    name: "Mecanicos",
    slug: "mecanicos",
    description: "Diagnostico, revisao, freios, suspensao e atendimento local.",
    icon: Wrench,
    professionals: 112,
    group: "Servicos automotivos",
    subcategories: ["guincho", "lavagem-automotiva"],
  },
  {
    name: "Pedreiros",
    slug: "pedreiros",
    description: "Obras, alvenaria, reboco, pisos e pequenas reformas.",
    icon: BrickWall,
    professionals: 203,
    group: "Construcao e reformas",
    subcategories: ["reformas", "reparos-em-geral"],
  },
  {
    name: "Pintores",
    slug: "pintores",
    description: "Pintura residencial, comercial, textura e acabamento fino.",
    icon: Brush,
    professionals: 167,
    group: "Casa e manutencao",
  },
  {
    name: "Montadores",
    slug: "montadores",
    description: "Moveis planejados, guarda-roupas, paineis e ajustes.",
    icon: Drill,
    professionals: 94,
    group: "Casa e manutencao",
    subcategories: ["montagem-desmontagem-mudanca", "transporte-de-moveis"],
  },
  {
    name: "Reformas",
    slug: "reformas",
    description: "Renovacao completa, planejamento, mao de obra e entrega.",
    icon: Hammer,
    professionals: 76,
    group: "Construcao e reformas",
  },
  {
    name: "Tecnicos",
    slug: "tecnicos",
    description: "Eletrodomesticos, ar-condicionado, maquinas e assistencia.",
    icon: Settings,
    professionals: 128,
    group: "Servicos tecnicos",
  },
  {
    name: "Frete",
    slug: "frete",
    description: "Transporte local de objetos, moveis, volumes e cargas leves.",
    icon: Truck,
    professionals: 88,
    group: "Transporte e entregas",
    subcategories: ["carreto", "pequenos-transportes", "transporte-de-moveis"],
  },
  {
    name: "Carreto",
    slug: "carreto",
    description: "Carretos rapidos para pequenas cargas, compras e retiradas.",
    icon: Truck,
    professionals: 64,
    group: "Transporte e entregas",
    parentSlug: "frete",
  },
  {
    name: "Mudanca residencial",
    slug: "mudanca-residencial",
    description: "Mudancas de casas e apartamentos com apoio no transporte.",
    icon: Home,
    professionals: 71,
    group: "Mudancas",
    subcategories: ["montagem-desmontagem-mudanca", "transporte-de-moveis"],
  },
  {
    name: "Mudanca comercial",
    slug: "mudanca-comercial",
    description: "Mudancas para escritorios, lojas, estoques e pequenos negocios.",
    icon: ClipboardCheck,
    professionals: 42,
    group: "Mudancas",
  },
  {
    name: "Montagem e desmontagem para mudanca",
    slug: "montagem-desmontagem-mudanca",
    description: "Desmontagem, protecao e montagem de moveis durante mudancas.",
    icon: Drill,
    professionals: 58,
    group: "Mudancas",
    parentSlug: "mudanca-residencial",
  },
  {
    name: "Entrega rapida",
    slug: "entrega-rapida",
    description: "Entregas expressas de documentos, compras e pequenos pacotes.",
    icon: Package,
    professionals: 120,
    group: "Transporte e entregas",
    subcategories: ["motoboy", "motofrete"],
  },
  {
    name: "Motoboy",
    slug: "motoboy",
    description: "Coletas e entregas urbanas com agilidade por moto.",
    icon: Bike,
    professionals: 96,
    group: "Transporte e entregas",
    parentSlug: "entrega-rapida",
  },
  {
    name: "Motofrete",
    slug: "motofrete",
    description: "Transporte profissional de pequenos volumes por motocicleta.",
    icon: Bike,
    professionals: 83,
    group: "Transporte e entregas",
    parentSlug: "entrega-rapida",
  },
  {
    name: "Transporte de moveis",
    slug: "transporte-de-moveis",
    description: "Transporte de sofas, camas, mesas, armarios e moveis avulsos.",
    icon: Truck,
    professionals: 77,
    group: "Transporte e entregas",
    parentSlug: "frete",
  },
  {
    name: "Transporte de eletrodomesticos",
    slug: "transporte-de-eletrodomesticos",
    description: "Transporte cuidadoso de geladeiras, fogoes, maquinas e equipamentos.",
    icon: Truck,
    professionals: 53,
    group: "Transporte e entregas",
    parentSlug: "frete",
  },
  {
    name: "Pequenos transportes",
    slug: "pequenos-transportes",
    description: "Leva e traz de itens menores, compras, caixas e objetos pessoais.",
    icon: Package,
    professionals: 69,
    group: "Transporte e entregas",
    parentSlug: "frete",
  },
  {
    name: "Guincho",
    slug: "guincho",
    description: "Guincho para carros, motos, pane, remocao e apoio emergencial.",
    icon: Car,
    professionals: 38,
    group: "Servicos automotivos",
  },
  {
    name: "Lavagem automotiva",
    slug: "lavagem-automotiva",
    description: "Lavagem, higienizacao e cuidados automotivos sob agendamento.",
    icon: Sparkles,
    professionals: 61,
    group: "Servicos automotivos",
  },
  {
    name: "Marido de aluguel",
    slug: "marido-de-aluguel",
    description: "Pequenos reparos, instalacoes, ajustes e manutencao domestica.",
    icon: Wrench,
    professionals: 145,
    group: "Casa e manutencao",
    subcategories: ["faz-tudo", "instalacao-em-geral", "reparos-em-geral"],
  },
  {
    name: "Faz-tudo",
    slug: "faz-tudo",
    description: "Servicos variados de manutencao, ajustes e pequenos consertos.",
    icon: Hammer,
    professionals: 132,
    group: "Casa e manutencao",
    parentSlug: "marido-de-aluguel",
  },
  {
    name: "Instalacao em geral",
    slug: "instalacao-em-geral",
    description: "Instalacao de suportes, prateleiras, cortinas, chuveiros e itens diversos.",
    icon: Drill,
    professionals: 118,
    group: "Casa e manutencao",
    parentSlug: "marido-de-aluguel",
  },
  {
    name: "Reparos em geral",
    slug: "reparos-em-geral",
    description: "Consertos simples, ajustes, manutencao preventiva e pequenas correcoes.",
    icon: Wrench,
    professionals: 156,
    group: "Casa e manutencao",
    parentSlug: "marido-de-aluguel",
  },
  {
    name: "Limpeza",
    slug: "limpeza",
    description: "Limpeza residencial, pos-obra, comercial e organizacao de ambientes.",
    icon: Sparkles,
    professionals: 104,
    group: "Limpeza e cuidados",
  },
  {
    name: "Beleza",
    slug: "beleza",
    description: "Servicos autonomos de beleza, bem-estar e atendimento domiciliar.",
    icon: Scissors,
    professionals: 92,
    group: "Beleza e bem-estar",
  },
  {
    name: "Cuidados",
    slug: "cuidados",
    description: "Apoio, acompanhamento, cuidados pessoais e servicos de rotina.",
    icon: HeartHandshake,
    professionals: 47,
    group: "Limpeza e cuidados",
  },
  {
    name: "Verificados",
    slug: "verificados",
    description: "Profissionais com documentos e historico revisados.",
    icon: BadgeCheck,
    professionals: 351,
    group: "Confianca",
  },
];

export const publicCategories = categories.filter((category) => category.slug !== "verificados");

export const workers: Worker[] = [
  {
    name: "Carlos Mendes",
    slug: "carlos-mendes-eletricista",
    role: "Eletricista residencial e predial",
    headline: "Instalacoes eletricas seguras com laudo, garantia e atendimento rapido.",
    bio: "Atendo residencias, condominios e pequenos comercios com foco em seguranca, organizacao e diagnostico claro antes da execucao. Trabalho com quadros, tomadas, iluminacao, padrao de entrada e manutencao preventiva.",
    city: "Sao Paulo",
    neighborhood: "Tatuape",
    rating: 4.9,
    reviewsCount: 86,
    jobsDone: 312,
    responseTime: "Responde em ate 20 min",
    verified: true,
    available: true,
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=80",
    services: ["Quadro de energia", "Instalacao de tomadas", "Iluminacao", "Emergencia eletrica"],
    categories: ["eletricistas", "verificados"],
    areas: ["Tatuape", "Mooca", "Vila Formosa", "Carriao"],
    yearsExperience: 12,
    whatsapp: "+5511999991001",
    phone: "+551133331001",
    startingPrice: "Visita tecnica a partir de R$ 90",
    contactSettings: {
      showWhatsapp: true,
      showPhone: true,
      allowQuotes: true,
      allowShare: true,
    },
    identityVerification: {
      status: "aprovado",
      retryCount: 0,
      recoveryEnabled: true,
      captureSource: "webcam",
      submittedAt: "15 abr 2026",
    },
    trustVerification: {
      status: "verificado",
      badgeEnabled: true,
      protectionLevel: "reforcado",
    },
    trustSignals: [
      { label: "Identidade verificada", status: "verificado" },
      { label: "Telefone verificado", status: "verificado" },
      { label: "Endereco verificado", status: "verificado" },
      { label: "Verificacao facial concluida", status: "verificado" },
      { label: "Portfolio verificado", status: "verificado" },
      { label: "Experiencia comprovada", status: "verificado" },
      { label: "Certificados enviados", status: "pendente" },
      { label: "Formacao informada", status: "nao_informado" },
    ],
    profileStrength: {
      experienceSummary: "Atua com instalacoes, manutencao preventiva e atendimentos emergenciais em residencias, condominios e pequenos comercios.",
      courseSummary: "NR10, comandos eletricos e seguranca em baixa tensao",
      qualifications: [{ title: "NR10 Basico", institution: "SENAI", year: "2024", type: "CERTIFICATION", verified: true }],
    },
    portfolio: [
      {
        title: "Modernizacao de quadro eletrico",
        description: "Troca de disjuntores, identificacao de circuitos e reorganizacao segura.",
        image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
        verified: true,
        workerVisible: true,
        evidenceLabel: "atividade real",
      },
      {
        title: "Iluminacao de cozinha planejada",
        description: "Pontos embutidos, fita LED e interruptores independentes.",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
        verified: true,
        evidenceLabel: "resultado final",
      },
    ],
    reviews: [
      {
        author: "Mariana A.",
        rating: 5,
        title: "Servico limpo e pontual",
        comment: "Explicou o problema, trouxe os materiais certos e deixou tudo funcionando no mesmo dia.",
        date: "12 abr 2026",
      },
      {
        author: "Ricardo T.",
        rating: 5,
        title: "Resolveu uma emergencia",
        comment: "Chegou rapido no apartamento e corrigiu um curto no quadro com muita transparencia.",
        date: "29 mar 2026",
      },
    ],
  },
  {
    name: "Fernanda Rocha",
    slug: "fernanda-rocha-reformas",
    role: "Reformas e acabamento",
    headline: "Reformas residenciais com cronograma, acabamento fino e comunicacao diaria.",
    bio: "Coordeno equipes para reformas de apartamentos, cozinhas, banheiros e ambientes comerciais. Antes de iniciar, entrego escopo, prazo e lista de materiais para evitar surpresa no meio da obra.",
    city: "Sao Paulo",
    neighborhood: "Pinheiros",
    rating: 4.8,
    reviewsCount: 64,
    jobsDone: 148,
    responseTime: "Responde hoje",
    verified: true,
    available: true,
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    services: ["Reforma de banheiro", "Pisos e revestimentos", "Gesso", "Pintura final"],
    categories: ["reformas", "pedreiros", "pintores", "verificados"],
    areas: ["Pinheiros", "Jardins", "Vila Madalena", "Perdizes"],
    yearsExperience: 9,
    whatsapp: "+5511999991002",
    phone: "+551133331002",
    startingPrice: "Orcamento tecnico sob visita",
    contactSettings: {
      showWhatsapp: true,
      showPhone: false,
      allowQuotes: true,
      allowShare: true,
    },
    identityVerification: {
      status: "aprovado",
      retryCount: 1,
      recoveryEnabled: true,
      captureSource: "upload",
      submittedAt: "11 abr 2026",
    },
    trustVerification: {
      status: "verificado",
      badgeEnabled: true,
      protectionLevel: "reforcado",
    },
    trustSignals: [
      { label: "Identidade verificada", status: "verificado" },
      { label: "Telefone verificado", status: "verificado" },
      { label: "Endereco verificado", status: "verificado" },
      { label: "Verificacao facial concluida", status: "verificado" },
      { label: "Portfolio verificado", status: "verificado" },
      { label: "Experiencia comprovada", status: "verificado" },
      { label: "Certificados enviados", status: "verificado" },
      { label: "Formacao informada", status: "pendente" },
    ],
    profileStrength: {
      experienceSummary: "Coordena reforma residencial e comercial com cronograma, equipe enxuta e controle de acabamento.",
      educationLevel: "Ensino tecnico",
      courseSummary: "Impermeabilizacao, revestimentos e gestao de obra enxuta",
      qualifications: [{ title: "Curso de impermeabilizacao", institution: "Instituto da Construcao", year: "2023", type: "COURSE", verified: true }],
    },
    portfolio: [
      {
        title: "Banheiro completo em 18 dias",
        description: "Demolicao, impermeabilizacao, porcelanato, metais e pintura.",
        image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
        verified: true,
        workerVisible: true,
        evidenceLabel: "profissional no local",
      },
      {
        title: "Sala integrada renovada",
        description: "Nivelamento de piso, pintura, iluminacao e acabamento em gesso.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
        verified: true,
        evidenceLabel: "resultado final",
      },
    ],
    reviews: [
      {
        author: "Paulo C.",
        rating: 5,
        title: "Obra organizada",
        comment: "A equipe cumpriu o cronograma e manteve o apartamento limpo ao final de cada etapa.",
        date: "03 abr 2026",
      },
      {
        author: "Renata L.",
        rating: 4,
        title: "Acabamento excelente",
        comment: "Gostei muito do cuidado com detalhes e da clareza nos custos extras.",
        date: "16 mar 2026",
      },
    ],
  },
  {
    name: "Joao Batista",
    slug: "joao-batista-encanador",
    role: "Encanador e cacador de vazamentos",
    headline: "Reparo hidraulico sem quebra desnecessaria e atendimento para condominios.",
    bio: "Especialista em vazamentos, pressurizadores, caixas acopladas, registros, aquecedores e manutencao hidraulica preventiva. Atendo com ferramentas de diagnostico e relatorio fotografico.",
    city: "Santo Andre",
    neighborhood: "Centro",
    rating: 4.7,
    reviewsCount: 51,
    jobsDone: 221,
    responseTime: "Responde em ate 1 h",
    verified: false,
    available: true,
    image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1600&q=80",
    services: ["Vazamentos", "Caixa acoplada", "Registros", "Pressurizador"],
    categories: ["encanadores"],
    areas: ["Centro", "Campestre", "Jardim", "Sao Bernardo"],
    yearsExperience: 15,
    whatsapp: "+5511999991003",
    phone: "+551133331003",
    startingPrice: "Diagnostico a partir de R$ 120",
    contactSettings: {
      showWhatsapp: true,
      showPhone: true,
      allowQuotes: true,
      allowShare: true,
    },
    identityVerification: {
      status: "em_analise",
      retryCount: 0,
      recoveryEnabled: false,
      captureSource: "upload",
      submittedAt: "19 abr 2026",
    },
    trustVerification: {
      status: "em_analise",
      badgeEnabled: false,
      protectionLevel: "padrao",
    },
    portfolio: [
      {
        title: "Correção de vazamento interno",
        description: "Identificacao do ponto e reparo localizado em parede de banheiro.",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80",
        city: "Santo Andre",
      },
      {
        title: "Instalacao de pressurizador",
        description: "Adequacao de tubulacao e ajuste de pressao para apartamento.",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=900&q=80",
        city: "Santo Andre",
      },
    ],
    reviews: [
      {
        author: "Andreia F.",
        rating: 5,
        title: "Diagnostico preciso",
        comment: "Encontrou o vazamento sem quebrar tudo e resolveu com rapidez.",
        date: "08 abr 2026",
      },
    ],
  },
  {
    name: "Rafael Oliveira",
    slug: "rafael-oliveira-frete-mudancas",
    role: "Frete, carreto e pequenas mudancas",
    headline: "Transporte de moveis, eletrodomesticos e pequenos volumes com cuidado e pontualidade.",
    bio: "Atendo fretes, carretos, pequenas mudancas residenciais e transporte de eletrodomesticos. Trabalho com protecao de itens, amarracao segura e combinacao clara de horarios, ajudantes e pontos de retirada.",
    city: "Sao Paulo",
    neighborhood: "Mooca",
    rating: 4.9,
    reviewsCount: 43,
    jobsDone: 176,
    responseTime: "Responde em ate 1 h",
    verified: true,
    available: true,
    image: "https://images.unsplash.com/photo-1616432043562-3671ea2e5242?auto=format&fit=crop&w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1600&q=80",
    services: ["Frete local", "Carreto", "Transporte de moveis", "Transporte de eletrodomesticos"],
    categories: ["frete", "carreto", "mudanca-residencial", "transporte-de-moveis", "transporte-de-eletrodomesticos", "pequenos-transportes", "verificados"],
    areas: ["Mooca", "Tatuape", "Ipiranga", "Vila Prudente"],
    yearsExperience: 7,
    whatsapp: "+5511999991004",
    phone: "+551133331004",
    startingPrice: "Fretes a partir de R$ 120",
    contactSettings: {
      showWhatsapp: true,
      showPhone: true,
      allowQuotes: true,
      allowShare: true,
    },
    identityVerification: {
      status: "em_analise",
      retryCount: 1,
      recoveryEnabled: false,
      captureSource: "webcam",
      submittedAt: "18 abr 2026",
    },
    trustVerification: {
      status: "em_analise",
      badgeEnabled: false,
      protectionLevel: "padrao",
    },
    portfolio: [
      {
        title: "Transporte de sofa e rack",
        description: "Retirada em apartamento com protecao das pecas e entrega no mesmo dia.",
        image: "https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
      },
      {
        title: "Pequena mudanca residencial",
        description: "Caixas, eletrodomesticos e moveis avulsos transportados com ajudante.",
        image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
      },
    ],
    reviews: [
      {
        author: "Luciana M.",
        rating: 5,
        title: "Frete cuidadoso",
        comment: "Chegou no horario, protegeu os moveis e entregou tudo sem dano.",
        date: "11 abr 2026",
      },
    ],
  },
  {
    name: "Bianca Nunes",
    slug: "bianca-nunes-entregas-motoboy",
    role: "Motoboy e entregas rapidas",
    headline: "Coletas e entregas expressas para documentos, pequenos pacotes e compras locais.",
    bio: "Realizo entregas rapidas, motofrete e rotas locais para empresas e clientes finais. Confirmo coleta, envio atualizacoes durante o trajeto e priorizo prazos combinados com transparencia.",
    city: "Sao Paulo",
    neighborhood: "Vila Mariana",
    rating: 4.8,
    reviewsCount: 57,
    jobsDone: 420,
    responseTime: "Responde em ate 20 min",
    verified: true,
    available: true,
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?auto=format&fit=crop&w=1600&q=80",
    services: ["Entrega rapida", "Motoboy", "Motofrete", "Pequenos transportes"],
    categories: ["entrega-rapida", "motoboy", "motofrete", "pequenos-transportes", "verificados"],
    areas: ["Vila Mariana", "Centro", "Paulista", "Saude"],
    yearsExperience: 5,
    whatsapp: "+5511999991005",
    phone: "+551133331005",
    startingPrice: "Entregas a partir de R$ 25",
    contactSettings: {
      showWhatsapp: true,
      showPhone: true,
      allowQuotes: true,
      allowShare: true,
    },
    identityVerification: {
      status: "aprovado",
      retryCount: 0,
      recoveryEnabled: true,
      captureSource: "webcam",
      submittedAt: "09 abr 2026",
    },
    trustVerification: {
      status: "verificado",
      badgeEnabled: true,
      protectionLevel: "reforcado",
    },
    portfolio: [
      {
        title: "Rota de entregas comerciais",
        description: "Coletas em tres pontos e entregas organizadas por prioridade.",
        image: "https://images.unsplash.com/photo-1591768793355-74d04bb6608f?auto=format&fit=crop&w=900&q=80",
        city: "Sao Paulo",
      },
    ],
    reviews: [
      {
        author: "Empresa Alfa",
        rating: 5,
        title: "Entrega rapida de documentos",
        comment: "Comunicacao clara e entrega antes do prazo combinado.",
        date: "05 abr 2026",
      },
    ],
  },
  {
    name: "Dona Cida Servicos",
    slug: "dona-cida-faz-tudo-limpeza",
    role: "Faz-tudo, limpeza e pequenos reparos",
    headline: "Apoio domestico para organizacao, limpeza, instalacoes simples e manutencao leve.",
    bio: "Atendo casas e apartamentos com limpeza, organizacao, pequenos reparos, instalacao de itens simples e ajuda em rotinas domesticas. Trabalho com combinados claros, cuidado com o ambiente e foco em confianca.",
    city: "Osasco",
    neighborhood: "Centro",
    rating: 4.7,
    reviewsCount: 32,
    jobsDone: 98,
    responseTime: "Responde hoje",
    verified: false,
    available: true,
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80",
    coverImage: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=1600&q=80",
    services: ["Limpeza residencial", "Faz-tudo", "Reparos em geral", "Instalacao em geral"],
    categories: ["limpeza", "faz-tudo", "marido-de-aluguel", "reparos-em-geral", "instalacao-em-geral"],
    areas: ["Centro", "Presidente Altino", "Bela Vista", "Jaguaribe"],
    yearsExperience: 10,
    whatsapp: "+5511999991006",
    phone: "+551133331006",
    startingPrice: "Diarias a partir de R$ 180",
    contactSettings: {
      showWhatsapp: true,
      showPhone: false,
      allowQuotes: true,
      allowShare: true,
    },
    identityVerification: {
      status: "rejeitado",
      retryCount: 2,
      recoveryEnabled: false,
      captureSource: "upload",
      submittedAt: "17 abr 2026",
      reviewNotes: "Imagem desfocada. Envie nova captura com melhor iluminacao.",
    },
    trustVerification: {
      status: "rejeitado",
      badgeEnabled: false,
      protectionLevel: "padrao",
    },
    portfolio: [
      {
        title: "Organizacao pos-mudanca",
        description: "Limpeza, organizacao de cozinha e pequenos ajustes apos mudanca.",
        image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
        city: "Osasco",
      },
    ],
    reviews: [
      {
        author: "Camila R.",
        rating: 5,
        title: "Muito capricho",
        comment: "Ajudou na organizacao e ainda resolveu pequenos reparos que estavam pendentes.",
        date: "21 mar 2026",
      },
    ],
  },
];

export const quotes: Quote[] = [
  {
    id: "ORC-1048",
    service: "Troca de quadro eletrico",
    worker: "Carlos Mendes",
    client: "Mariana Almeida",
    location: "Tatuape, Sao Paulo",
    status: "Aberto",
    createdAt: "Hoje, 10:42",
  },
  {
    id: "ORC-1047",
    service: "Reforma de banheiro",
    worker: "Fernanda Rocha",
    client: "Paulo Cesar",
    location: "Pinheiros, Sao Paulo",
    status: "Respondido",
    value: "R$ 8.900",
    createdAt: "Ontem, 17:18",
  },
  {
    id: "ORC-1046",
    service: "Caca vazamento",
    worker: "Joao Batista",
    client: "Andreia Freitas",
    location: "Centro, Santo Andre",
    status: "Aprovado",
    value: "R$ 460",
    createdAt: "16 abr 2026",
  },
];

export function getWorkerBySlug(slug: string) {
  return workers.find((worker) => worker.slug === slug);
}

export function searchWorkers(params: {
  service?: string;
  city?: string;
  neighborhood?: string;
}) {
  return filterWorkers(workers, params).map((result) => result.worker);
}
