export const routes = {
  home: "/",
  search: "/buscar",
  categories: "/categorias",
  category: (slug: string) => `/categorias/${slug}`,
  about: "/sobre",
  contact: "/contato",
  terms: "/termos",
  privacy: "/privacidade",
  howItWorks: "/como-funciona",
  login: "/entrar",
  postLogin: "/pos-login",
  recoverPassword: "/recuperar-senha",
  register: "/cadastro",
  registerClient: "/cadastro/cliente",
  registerWorker: "/cadastro/profissional",
  clientDashboard: "/painel/cliente",
  clientFavorites: "/painel/cliente/favoritos",
  clientQuotes: "/painel/cliente/orcamentos",
  clientProfile: "/painel/cliente/perfil",
  clientPreferences: "/painel/cliente/preferencias",
  clientNotifications: "/painel/cliente/notificacoes",
  clientSettings: "/painel/cliente/configuracoes",
  workerDashboard: "/painel/profissional",
  workerProfileSettings: "/painel/profissional/perfil",
  workerServices: "/painel/profissional/servicos",
  workerAvailability: "/painel/profissional/disponibilidade",
  workerPortfolio: "/painel/profissional/portfolio",
  workerQuotes: "/painel/profissional/orcamentos",
  workerReviews: "/painel/profissional/avaliacoes",
  workerNotifications: "/painel/profissional/notificacoes",
  workerSettings: "/painel/profissional/configuracoes",
  admin: "/admin",
  adminUsers: "/admin/usuarios",
  adminClients: "/admin/clientes",
  adminCategories: "/admin/categorias",
  adminWorkers: "/admin/profissionais",
  adminQuotes: "/admin/orcamentos",
  adminReviews: "/admin/avaliacoes",
  adminModeration: "/admin/moderacao",
  adminVerification: "/admin/verificacoes",
  adminSettings: "/admin/configuracoes",
  workerProfile: (slug: string) => `/profissionais/${slug}`,
} as const;
